-- Migration D5 (s177) — assemblages_runes : colonne `duree` + nettoyage descriptions
-- Régénérée à l'identique depuis l'état prod (migration déjà appliquée via MCP le 2026-06-13).
-- Idempotente : ADD COLUMN IF NOT EXISTS + UPDATE par `nom` (rejouables).
-- Méthode : 15 UPDATE explicites par ligne (PAS de regex — chaînes hétérogènes,
-- contenu visible joueur, certitude 100 %). Durées = valeurs du manuel (aucune inventée).
-- Préservation/Santé : on GARDE le mécanisme de déclenchement dans le narratif,
-- la colonne `duree` porte le « ou déclenchement ».

ALTER TABLE assemblages_runes ADD COLUMN IF NOT EXISTS duree text;

UPDATE assemblages_runes SET duree = '30 min', description = '+2 niveaux pour résister aux sorts.', description_longue = 'Privilégié pour ses capacités à renforcer l''endurance mentale de son porteur, souvent associé à la détermination. Cet assemblage, une fois activé, offre à son porteur un bonus de 2 niveaux supplémentaires pour résister aux sorts.' WHERE nom = 'Assemblage de barrière magique';
UPDATE assemblages_runes SET duree = '30 min', description = 'Rend le bouclier ou l''arme indestructible.', description_longue = 'Utilisée largement comme bénédiction sur les instruments de minage des peuples nains. Lorsque cet assemblage est activé, le bouclier ou l''arme qui le porte devient indestructible.' WHERE nom = 'Assemblage de durabilité';
UPDATE assemblages_runes SET duree = '30 min', description = 'Protège contre paralysie et enchevêtrement.', description_longue = 'Longtemps utilisé par les explorateurs de région sauvage et par les marchands de grand chemin. Cet assemblage, lorsqu''il est activé, protège contre les effets de paralysie ou d''enchevêtrement qui peuvent affecter son porteur.' WHERE nom = 'Assemblage de liberté';
UPDATE assemblages_runes SET duree = '2 h ou déclenchement', description = 'Protège contre le prochain coup de grâce reçu.', description_longue = 'Un dirigeant important serait à l''origine de cet assemblage, craignant sa mort aux mains de son frère. Une fois tracé, il protège son porteur contre le prochain coup de grâce reçu. Dès qu''il annule un coup de grâce, l''effet se termine. Un personnage protégé reste inconscient pendant la durée complète de son coma — les guérisons, même magiques, ne peuvent pas le guérir.' WHERE nom = 'Assemblage de préservation';
UPDATE assemblages_runes SET duree = '1 h', description = 'Temps de forge réduit de moitié.', description_longue = 'Cette combinaison de runes a été découverte par accident en tentant de renforcer des outils de forge. Cet assemblage peut être fait sur un marteau de forge ou une enclume. Une fois activé, tous les temps de production, de réparation ou de renforcement sont réduits de moitié si le forgeron utilise l''objet porteur de l''assemblage.' WHERE nom = 'Assemblage de productivité';
UPDATE assemblages_runes SET duree = '1 h', description = 'Réduction de 1 dégât de feu/glace/acide/foudre.', description_longue = 'De nombreuses expéditions ont été entreprises grâce à cet assemblage. Lorsqu''il est activé, il donne au joueur une réduction de dommage de 1 sur les dégâts de feu, glace, acide, électricité ou de vent qu''il reçoit.' WHERE nom = 'Assemblage de protection contre les éléments';
UPDATE assemblages_runes SET duree = '1 h', description = '+2 niveau vs Magie Noire/Nécromancie, +1 résistance aux dégâts de ces cercles.', description_longue = 'Bien que la création de cet assemblage fut nécessaire durant la guerre d''Heimrook, il reste un mal nécessaire. Une fois activé, il donne +2 sur le niveau du personnage pour résister aux sorts du cercle de Magie Noire (Nothogh) et de Nécromancie (Thork). De plus, il offre une résistance de 1 aux dégâts de ces cercles (drain-life, énergie négative).' WHERE nom = 'Assemblage de protection du mal';
UPDATE assemblages_runes SET duree = '1 h', description = '+1 PV supplémentaire à chaque guérison reçue.', description_longue = 'Vastement utilisé sur tous blessés ou malades lorsqu''un connaisseur des runes est présent. Une fois activé, le porteur de cet assemblage gagne toujours un point de vie supplémentaire lorsqu''il reçoit des guérisons.' WHERE nom = 'Assemblage de régénération';
UPDATE assemblages_runes SET duree = '1 h', description = 'Ne peut être transformé en mort-vivant.', description_longue = 'Ce cumulatif de runes est posé sur le front des décédés, leur assurant un passage digne et sans embûches. Ses bénéfices s''étendent aussi aux vivants. Une fois activé, le personnage ne peut plus être transformé en mort-vivant. Ne protège pas contre la possession.' WHERE nom = 'Assemblage de repos en paix';
UPDATE assemblages_runes SET duree = '1 h', description = 'Offre +1 PV temporaire.', description_longue = 'Cette combinaison de runes a été souvent utilisée pendant les périodes de guerre et lors des expéditions visant à accroître le réseau minier des nains. L''enchantement de ces runes offre une endurance nouvelle aux individus qui les portent, plus résistants et plus robustes. Une fois activé, l''assemblage offre 1 point de vie temporaire supplémentaire à son porteur. Ce point de vie peut être guéri normalement pour toute la durée de l''effet.' WHERE nom = 'Assemblage de résilience';
UPDATE assemblages_runes SET duree = '2 h', description = '+1 point d''armure.', description_longue = 'Populaire parmi les forgerons ainsi que les marchands d''armures de seconde main. Une fois activé, l''assemblage offre 1 point d''armure supplémentaire à l''armure. Ce point d''armure peut être réparé normalement pour toute la durée de l''effet. Une fois l''effet terminé, le point d''armure obtenu par l''assemblage disparaît.' WHERE nom = 'Assemblage de rigidité';
UPDATE assemblages_runes SET duree = '1 h ou déclenchement', description = 'Protège contre un poison ou maladie mineur/intermédiaire (1 résistance).', description_longue = 'Les textes originaux décrivent cet assemblage porté par les prêtres guérisseurs leur permettant de soigner des patients hautement contagieux. Une fois activé, il protège son porteur contre un poison ou une maladie de niveau mineur ou intermédiaire, et se dissipe après avoir résisté au prochain poison ou à la prochaine maladie.' WHERE nom = 'Assemblage de santé';
UPDATE assemblages_runes SET duree = '1 h', description = 'Voit auras magiques (comme Détection magie), +2 résistance illusions.', description_longue = 'Un fameux magicien nain serait le concepteur de cet assemblage, utilisé par plusieurs marchands de grand chemin. Une fois activé, il permet au personnage de voir les auras magiques des objets qu''il touche, comme un sort à effet égal à son niveau (détection de magie uniquement, pas d''identification). Il obtient également +2 de résistance contre les sorts à effet de l''école de l''Illusion (Guerben).' WHERE nom = 'Assemblage de vision pure';
UPDATE assemblages_runes SET duree = '1 cycle', description = 'Augmente le nombre de combats maximal de l''armure de 1.', description_longue = 'Cet assemblage est principalement utilisé par les constructeurs nains comme symbole de protection. Une fois activé, il augmente le nombre de combats maximal de l''armure de 1. Une fois l''enchantement terminé, l''armure coûte deux pépites supplémentaires de chaque matériau lors de sa prochaine réparation.' WHERE nom = 'Assemblage du bâtisseur';
UPDATE assemblages_runes SET duree = '1 min', description = 'Intangible.', description_longue = 'Cet assemblage fut des plus utiles durant la guerre de Heimrook, laissant les prêtres nains obtenir de l''information cruciale. Une fois activé, il permet au porteur de passer dans l''univers éthéré, devenant intangible.' WHERE nom = 'Assemblage du passage';
