-- Abrégés (resume_condense) des cercles Magie Noire et Nécromancie — 24 sorts (FICHES Phase 3, s269) — DERNIER LOT (136/136)
-- Idempotent : UPDATE ancré sur nom + cercle (rejouable à froid → même état). Champs resume_condense vides au départ = ajout pur, aucun intégral (description) touché.

-- ===== MAGIE NOIRE (14) =====
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles un bouclier absorbant un nombre de dégâts d'énergie négative égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Bouclier contre l''Énergie négative' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Aveugle la ou les cibles pour la durée du sort.$abr$ WHERE nom = 'Cécité' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Rend la ou les cibles muettes pour la durée du sort.$abr$ WHERE nom = 'Perte de la Parole' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts d'énergie négative croissant avec le niveau : 1 au niveau 1, jusqu'à 8 au niveau 20.$abr$ WHERE nom = 'Rayon d''Énergie Négative' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Tord la ou les cibles de douleur : incapables d'attaquer ou d'incanter et peinant à se défendre.$abr$ WHERE nom = 'Souffrance' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Fait perdre à la ou les cibles un nombre de points de spiritualité égal au niveau du sort.$abr$ WHERE nom = 'Brûlure Spirituelle' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Assaille la cible de cauchemars toute la nuit suivante : à son réveil elle est épuisée et n'a récupéré aucun point de vie ni de spiritualité.$abr$ WHERE nom = 'Cauchemar' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Réduit les points de vie de la ou les cibles à 2 pour la durée ; niv. 11 : elles ne peuvent plus utiliser d'arme à deux mains ; niv. 20 : elles ne peuvent plus combattre, ni à l'arme ni au sort.$abr$ WHERE nom = 'Faiblesse' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Frappe la ou les cibles de l'état pestiféré qui plafonne leurs points de vie à 2 jusqu'à guérison par un sort de guérison des maladies de niveau supérieur (après quoi elles restent à 2 PV mais se soignent normalement) ; niv. 20 : elles deviennent contagieuses au toucher pour la durée, un même contact ne transmettant qu'une fois par fin de semaine.$abr$ WHERE nom = 'Pestilence' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Inflige l'état Saignement : la cible perd 1 point de vie par minute toute la durée — les soins referment une plaie mais une nouvelle s'ouvre aussitôt (le saignement reprend à la minute suivante) —, effet interrompu seulement par la fin du sort ou l'anti-magie ; la cible ne peut pas descendre sous 1 point de vie (les dégâts cessent à ce seuil et reprennent si elle se soigne).$abr$ WHERE nom = 'Saignée à blanc' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Alourdit la magie de la ou les cibles : chaque sort qu'elles lancent coûte des points de spiritualité supplémentaires — 1 (niv. 6), 2 (niv. 10), 3 (niv. 15), 4 (niv. 20).$abr$ WHERE nom = 'Saignée Mystique' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Plonge une zone choisie dans une obscurité totale qui aveugle tout personnage y entrant pour la durée ; +1 min gratuite par niveau au-delà de 6.$abr$ WHERE nom = 'Ténèbres' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Le lanceur interroge le Néant, qui répond toujours vrai, mais l'Abîme lui pose en retour une question à laquelle il doit répondre vrai — refuser ou mentir déclenche une malédiction choisie par le MJ : Reflet Falsifié (ne reconnaît plus son corps ni son reflet), Marque du Parjure (symbole noir sur la peau, indissimulable magiquement), La Faim du Vide (jamais rassasié, potions de soins ou de spiritualité réduites de moitié), Nom Oublié (ne se souvient plus de son vrai nom, ne peut ni le répéter ni l'écrire), ou autre au choix du MJ ; niv. 20 : deux questions de part et d'autre, deux mensonges entraînant deux malédictions.$abr$ WHERE nom = 'L''Entente du Néant' AND cercle = 'Magie Noire';
UPDATE sorts SET resume_condense = $abr$Crée une zone où tout sort de niveau inférieur au sort est neutralisé, sauf ceux de l'école de magie noire.$abr$ WHERE nom = 'Oraison Funeste' AND cercle = 'Magie Noire';

-- ===== NÉCROMANCIE (10) =====
UPDATE sorts SET resume_condense = $abr$Relève en mort-vivant sous son contrôle une ou des cibles comateuses ou mortes (les mortes ne résistent pas) — zombi (niv. 1), squelette (niv. 6), goule (niv. 11), puis blême ou spectre au choix (niv. 16), masques fournis par le joueur ; si le mort-vivant perd tous ses PV ou que le sort se termine, une cible qui était comateuse tombe inconsciente puis s'éveille après 1 minute sans mémoire.$abr$ WHERE nom = 'Animation des morts' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles un bouclier annulant un nombre de dégâts de vol de vie égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Bouclier Contre la Mort' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Permet d'interroger à voix haute un personnage mort (ni comateux ni inconscient) tant qu'il garde au moins sa tête, hors de tout combat impliquant le lanceur ou la cible, qui répond en détail à un nombre de questions selon le niveau — 1 (niv. 1), 2 (niv. 5), 3 (niv. 10), 4 (niv. 15), 5 (niv. 20) — avant que le corps retombe inanimé.$abr$ WHERE nom = 'Communication avec les Cadavres' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Inflige à tout mort-vivant visé un nombre de dégâts magiques égal au niveau du sort.$abr$ WHERE nom = 'Destruction des Morts-Vivants' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Donne à la ou les cibles l'apparence de la mort (plus de signes vitaux), sans les empêcher d'agir mais toute action évidente (mouvement ou parole) rompt le sort : simplement mortes (niv. 1), puis trompant la compétence Diagnostic 1 (niv. 6), Diagnostic 1 et 2 (niv. 11), Diagnostic 1, 2 et 3 (niv. 20).$abr$ WHERE nom = 'Masque Funèbre' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Rend tangibles la ou les cibles intangibles, sans qu'elles puissent le redevenir pour la durée du sort.$abr$ WHERE nom = 'Pieu Spirituel' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Soumet les morts-vivants visés, qui exécutent à la lettre les ordres du lanceur même au prix de leur destruction ; pour reprendre un mort-vivant déjà animé ou contrôlé, le sort doit dépasser le niveau de l'effet en place.$abr$ WHERE nom = 'Contrôle des morts-vivants' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts à une cible et rend au lanceur autant de points de vie (sans dépasser son maximum) : 1 (niv. 6), 2 (niv. 10), 3 (niv. 15), 4 (niv. 20, le lanceur pouvant alors transférer les points gagnés à une cible consentante à 5 pieds).$abr$ WHERE nom = 'Drain de vie' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Empêche les morts-vivants de niveau inférieur au sort d'attaquer la ou les cibles, qu'ils peuvent toutefois encore déplacer si elles leur barrent le chemin.$abr$ WHERE nom = 'Protection Contre les Morts-Vivants' AND cercle = 'Nécromancie';
UPDATE sorts SET resume_condense = $abr$Emprisonne l'âme d'un personnage mort (ni comateux ni inconscient) dans une pierre d'âme (objet en-jeu, qui libère l'âme si brisée), à condition que le sort égale ou dépasse le niveau de ce personnage.$abr$ WHERE nom = 'Capture d''Âmes' AND cercle = 'Nécromancie';
