-- Abrégés (resume_condense) des cercles Divination, Magie Pure et Protection — 29 sorts (FICHES Phase 3, s269)
-- Idempotent : UPDATE ancré sur nom + cercle (rejouable à froid → même état). Champs resume_condense vides au départ = ajout pur, aucun intégral (description) touché.

-- ===== DIVINATION (10) =====
UPDATE sorts SET resume_condense = $abr$Permet au lanceur de communiquer avec un esprit annoncé de son choix, qui dialogue pleinement sans pouvoir mentir, son efficacité dépendant de la nature de l'esprit ; nécessite un animateur.$abr$ WHERE nom = 'Contact avec les Esprits' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Confirme seulement la présence ou l'absence d'une aura magique, sans sa nature, sa puissance ni ses effets (sur un objet porté, le sort doit égaler ou dépasser le niveau du porteur), et identifie les fausses auras — mais ne perce une aura dissimulée ou falsifiée par un effet que s'il égale ou dépasse le niveau de cet effet.$abr$ WHERE nom = 'Détection de la magie' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Décèle et nomme les poisons, maladies et parasites affectant la ou les cibles, sans révéler leurs effets ni leur traitement : poisons mineurs (niv. 1), maladies mineures (niv. 5), poisons intermédiaires (niv. 6), maladies intermédiaires (niv. 10), poisons majeurs ou parasites (niv. 11), maladies majeures (niv. 15), puis tout de tout niveau (niv. 20).$abr$ WHERE nom = 'Détection des Toxines' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de comprendre et parler les langues qui leur sont inconnues ; +1 min gratuite par niveau au-delà de 1.$abr$ WHERE nom = 'Don des Langues' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Sonde le potentiel magique d'une cible — hors capacités venant d'objets, potions ou effets temporaires : révèle si elle peut lancer des sorts et leur origine, magique ou divine (niv. 1), ses écoles ou domaines (niv. 11), puis son niveau de maîtrise dans chacun (niv. 20).$abr$ WHERE nom = 'Sensibilité des Arcanes' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Immunise la ou les cibles contre les sorts d'Illusion de niveau inférieur ou égal au sort (annoncer « Résiste » à chaque illusion ainsi annulée).$abr$ WHERE nom = 'Vision Lucide' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Pose à une force supérieure un nombre de questions égal à la moitié du niveau du sort (arrondi à l'unité supérieure), chacune recevant un oui, un non ou une réponse indécise ; nécessite un animateur.$abr$ WHERE nom = 'Augure' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Scrute les assemblages runiques d'une cible : détecte ceux inscrits sur son corps (niv. 6) puis sur son équipement (niv. 10), les identifie tous (niv. 11), et au niv. 20 les bloque tous temporairement pendant 5 minutes.$abr$ WHERE nom = 'Détection runique' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Révèle les écoles et domaines des sorts actuellement actifs sur une cible, sans leurs effets, leur durée restante ni leur niveau.$abr$ WHERE nom = 'Vision de la magie' AND cercle = 'Divination';
UPDATE sorts SET resume_condense = $abr$Détecte et identifie une malédiction sur une cible — sa puissance et ses effets généraux, ou la certitude qu'il n'y en a aucune — sans pouvoir la lever ni la modifier : mineure (niv. 11), jusqu'aux intermédiaires (niv. 14), jusqu'aux majeures (niv. 18), avec en plus son origine — rituel, entité, objet ou sort (niv. 20).$abr$ WHERE nom = 'Connaissance des malédictions' AND cercle = 'Divination';

-- ===== MAGIE PURE (10) =====
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles des points d'armure égaux à la moitié du niveau du sort (arrondi à l'unité supérieure), à condition qu'elles ne portent aucune armure physique.$abr$ WHERE nom = 'Bouclier d''Énergie Spirituelle' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles un bouclier absorbant un nombre de dégâts de magie pure égal à la moitié du niveau du sort (arrondi à l'unité supérieure), sans protéger contre le drain de vie ni l'énergie négative.$abr$ WHERE nom = 'Bouclier Magique' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Enferme dans une bulle les créatures présentes dans la zone à l'incantation : elles s'y déplacent mais ne peuvent en sortir, et rien (créature, attaque ou sort) ne la franchit dans un sens ou l'autre — sauf qu'un personnage de niveau supérieur (ou qui résiste autrement) la perce en la traversant, mettant fin au sort.$abr$ WHERE nom = 'Bulle d''emprisonnement' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de renvoyer à son lanceur un sort ou une prière les visant, à condition qu'il soit de niveau inférieur à celui du miroir.$abr$ WHERE nom = 'Miroir' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts magiques croissant avec le niveau, capables d'atteindre les cibles intangibles : 1 au niveau 1, jusqu'à 8 au niveau 20.$abr$ WHERE nom = 'Projectile Magique' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Crée une zone annulant toute magie de niveau inférieur : les sorts qui la traversent sont sans effet et les pouvoirs d'un personnage se réactivent en sortant, tandis qu'un objet magique y perd aura et capacités et redevient destructible — objets atteints jusqu'au niveau 1 (niv. 6), 2 (niv. 11), 3 (niv. 20).$abr$ WHERE nom = 'Coquille d''anti-magie' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Retire des cibles tous les effets magiques actifs (sorts ou potions) de niveau inférieur au sort, sans agir sur les objets magiques.$abr$ WHERE nom = 'Dissipation de la magie' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Au toucher, inflige des dégâts magiques — capables d'atteindre une cible intangible — selon le niveau : 4 (niv. 6), 6 (niv. 10) ; aux niveaux 11 et 20, soit deux cibles à 4/5 dégâts chacune, soit une seule à 8/10.$abr$ WHERE nom = 'Explosion arcanique' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Transfère à une cible vivante une partie de l'énergie magique du lanceur (l'excédent au-delà du maximum de spiritualité de la cible est perdu) : 2 points (niv. 6), 3 (niv. 8), 4 (niv. 10), 5 (niv. 12), 6 (niv. 14), 7 (niv. 16), 8 (niv. 18), 10 (niv. 20) ; via un objet ou parchemin, ces points sont puisés dans la réserve de spiritualité de l'utilisateur de l'objet.$abr$ WHERE nom = 'Inspiration spirituel' AND cercle = 'Magie Pure';
UPDATE sorts SET resume_condense = $abr$Dissipe le premier sort dirigé contre le lanceur — bénéfique, à effet de niveau inférieur ou à dégâts — en lui rendant 1 point de spiritualité (annoncer « résiste »), sans effet sur les attaques physiques ni sur les sorts déjà actifs et seulement pour la part le visant directement ; niv. 20 : au choix, 1 point de spiritualité ou 1 point de vie.$abr$ WHERE nom = 'Absorption Magique' AND cercle = 'Magie Pure';

-- ===== PROTECTION (9) =====
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de résister aux pièges en utilisant le niveau du sort à la place du leur.$abr$ WHERE nom = 'Alerte du Danger' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Immunise la ou les cibles contre les effets d'enchevêtrement, de paralysie, de pétrification et de maladresse de niveau inférieur au sort — sans dissiper ceux déjà en cours ; +1 min gratuite par niveau au-delà de 1.$abr$ WHERE nom = 'Liberté de Mouvement' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Immunise la ou les cibles contre les effets de paralysie de niveau inférieur ou égal au sort (la pétrification reste un effet distinct, non couvert) ; +1 min gratuite par niveau au-delà de 6.$abr$ WHERE nom = 'Protection contre la Paralysie' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Encaisse sans dégât un nombre de coups d'armes conventionnelles non magiques selon le niveau — 1 (niv. 1), 2 (niv. 5), 3 (niv. 10), 4 (niv. 15), 5 (niv. 20) — les coups assommants comptant comme un coup normal ; protège aussi contre la prochaine attaque sournoise mais consomme alors toutes les protections restantes.$abr$ WHERE nom = 'Protection contre les Armes Conventionnelles' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de résister à l'Hypnose — niveau 1 (niv. 6), 2 (niv. 12), 3 (niv. 18) — en n'étant pas tenues de répondre et en pouvant mentir ou dire vrai sans annoncer « Résiste », afin de manipuler l'hypnotiseur.$abr$ WHERE nom = 'Esprit impénétrable' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Fait subir au lanceur, à la place de la cible qu'il garde en vue, les dégâts qu'elle recevrait ; +1 min gratuite par niveau au-delà de 6.$abr$ WHERE nom = 'Gardien Cabalistique' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Confère à la cible une protection bloquant un nombre de dégâts d'énergie négative et de drain de vie égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Protection contre les Effets Négatifs' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Empêche les personnages de niveau inférieur au sort d'approcher le lanceur à moins de 10 pieds, sans bloquer les sorts, prières ni armes à distance.$abr$ WHERE nom = 'Répulsion' AND cercle = 'Protection';
UPDATE sorts SET resume_condense = $abr$Empêche tout coup de grâce contre la cible, à moins qu'il soit de niveau supérieur au sort.$abr$ WHERE nom = 'Lien avec le monde vivant' AND cercle = 'Protection';
