-- Abrégés (resume_condense) des cercles Charmes, Combat et Illusion — 32 sorts (FICHES Phase 3, s269)
-- Idempotent : UPDATE ancré sur nom + cercle (rejouable à froid → même état). Champs resume_condense vides au départ = ajout pur, aucun intégral (description) touché.

-- ===== CHARMES (11) =====
UPDATE sorts SET resume_condense = $abr$Rend la ou les cibles amicales envers le lanceur : elles cessent de l'attaquer sans jamais sacrifier leur vie pour lui, l'effet prenant fin s'il se montre hostile envers elles.$abr$ WHERE nom = 'Amitié' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Rend la ou les cibles hostiles envers le lanceur : elles se mettent à le détester sans être forcées de l'attaquer ni aller jusqu'à le tuer.$abr$ WHERE nom = 'Antipathie' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Pousse la ou les cibles à s'emparer d'un objet visible choisi par le lanceur, par tous les moyens jusqu'au meurtre selon leur caractère, puis à le garder toute la durée — elles restent conscientes et gardent leurs souvenirs, et l'effet cesse si la cible tombe inconsciente.$abr$ WHERE nom = 'Avidité' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Force la ou les cibles à fixer leur attention sur le lanceur sans pouvoir détourner le regard ni l'ignorer, tant qu'il parle ou agit de façon théâtrale en continu (s'il s'arrête, l'effet cesse pour toutes) ; il cesse pour une cible donnée si elle subit des dégâts, est bousculée, secouée ou heurtée brusquement.$abr$ WHERE nom = 'Discours captivant' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Force la cible à exécuter à la lettre, sans initiative, un ordre de plus en plus contraignant : 5 mots sans mettre sa vie en danger (niv. 1), une phrase de 10 mots sauf blessure grave ou mort imminente (niv. 6) — souvenirs conservés à ces deux niveaux —, 15 mots sauf blessure ou mort imminente et sans aucun souvenir ensuite (niv. 11), 20 mots même au prix de blessures ou d'inconscience mais jamais le suicide (niv. 20) ; l'effet prend fin l'ordre accompli, la durée écoulée, ou si la cible devient inconsciente ou comateuse.$abr$ WHERE nom = 'Domination' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Effondre les capacités mentales de la cible : limitée à des phrases de 5 mots et à compter jusqu'à 5, elle ne peut plus lancer de sort ou prière ni utiliser de compétence, mais garde ses réflexes de survie et peut se défendre.$abr$ WHERE nom = 'Esprit du Simplet' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Prend la cible d'un rire incontrôlable : incapable d'attaquer ou d'incanter et peinant à se défendre ; niv. 11 : elle est en plus aveuglée.$abr$ WHERE nom = 'Fou Rire Incessant' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Soumet une créature vivante non humanoïde, qui considère le lanceur comme une autorité et tente d'obéir à ses instructions selon ses capacités, sans jamais se mettre en danger ni poser d'acte menant directement à sa mort.$abr$ WHERE nom = 'Envoûtement de Créature' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Rend la cible incapable de dire la vérité, à l'oral comme à l'écrit, et l'immunise contre les effets l'obligeant à dire la vérité de niveau inférieur pour la durée.$abr$ WHERE nom = 'Mensonge' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Efface définitivement un segment des souvenirs récents de la cible — 2 minutes (niv. 6), 5 (niv. 10), 10 (niv. 14), 15 (niv. 18), 30 (niv. 20) — qu'elle joue comme un blanc naturel comblé par des suppositions, sans savoir qu'elle a été affectée ; effet permanent, indétectable et non annulable par l'anti-magie, applicable une seule fois par événement à un même personnage.$abr$ WHERE nom = 'Oubli' AND cercle = 'Charmes';
UPDATE sorts SET resume_condense = $abr$Plonge la ou les cibles dans un sommeil profond dont elles s'éveillent au moindre dégât ou contact ; niv. 11 : elles peuvent être déplacées ou fouillées sans se réveiller.$abr$ WHERE nom = 'Sommeil' AND cercle = 'Charmes';

-- ===== COMBAT (10) =====
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles des points d'armure d'énergie temporaires, non récupérables une fois perdus et cumulés à une armure physique déjà portée : 1 (niv. 1), 2 (niv. 5), 3 (niv. 10), 4 (niv. 11), 5 (niv. 20).$abr$ WHERE nom = 'Armure' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Permet au lanceur de combattre normalement même aveuglé (il peut garder les yeux ouverts) ; +1 min gratuite par niveau au-delà de 6.$abr$ WHERE nom = 'Combat Aveugle' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Supprime la douleur sans réduire les dégâts ni les états subis : la cible ignore les effets liés à la douleur (niv. 1), devient insensible à la compétence Torture tant que le sort dure — les effets s'appliquant aussitôt s'il se termine en pleine séance (niv. 6) —, et n'est affectée par un sort basé sur la douleur que s'il dépasse le niveau du sort (niv. 11), ces effets étant cumulatifs.$abr$ WHERE nom = 'Insensibilité à la douleur' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Frappe la ou les cibles de peur : incapables d'attaquer ou de viser le lanceur, elles peuvent encore se défendre mais doivent fuir jusqu'à ne plus le voir (un guerrier double son niveau pour résister à la peur).$abr$ WHERE nom = 'Présence intimidante' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Contraint la cible à tout faire pour blesser le lanceur, l'effet cessant dès qu'elle lui a fait couler le sang.$abr$ WHERE nom = 'Provocation' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Immunise la ou les cibles contre les attaques par surprise (annoncer « Annule ») et réduit de moitié les dégâts des pièges : résiste à l'Égorgement et l'Assommement (niv. 1), au Brise-Cou (niv. 6), au Backstab (niv. 20, avec en plus le niveau de personnage doublé pour résister aux pièges, magiques ou non).$abr$ WHERE nom = 'Sens aiguisé' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Enchante un nombre d'armes égal aux cibles : elles infligent des dégâts magiques (niv. 6), deviennent indestructibles (niv. 10) puis insensibles à tout autre sort (niv. 15) ; niv. 20 : au choix, le lancer normal ou enchanter pour qu'elles frappent magique toutes les armes dans un rayon de 10 pieds, celles-ci restant toutefois destructibles et altérables.$abr$ WHERE nom = 'Arme Magique' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts de magie pure selon le niveau — 1 (niv. 6), 2 (niv. 11), 3 (niv. 16), 5 (niv. 20) — et peut être lancé en plein combat sans que le lanceur soit déconcentré par les dégâts qu'il subit.$abr$ WHERE nom = 'Lame Dimensionnelle' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de manier des armes à deux mains même sans la compétence d'armes pour la durée ; niv. 11 : elles ne peuvent plus être désarmées.$abr$ WHERE nom = 'Poigne de fer' AND cercle = 'Combat';
UPDATE sorts SET resume_condense = $abr$Dote chaque cible d'un bouclier qui annule les prochains sorts à dégâts reçus : 1 (niv. 11), 2 (niv. 15), 3 (niv. 20).$abr$ WHERE nom = 'Bouclier Mystique' AND cercle = 'Combat';

-- ===== ILLUSION (11) =====
UPDATE sorts SET resume_condense = $abr$Pose sur le ou les objets visés une fausse aura magique de nature choisie par le lanceur (sur un objet déjà magique, le sort doit dépasser le niveau de l'objet sinon il échoue), de niveau d'aura : 1 (niv. 1), 2 ou moins (niv. 6), 3 ou moins (niv. 11), 4 ou moins (niv. 20).$abr$ WHERE nom = 'Aura magique' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Remplace la prémonition d'une cible : lorsqu'elle utilise la compétence « Rêves », elle reçoit la vision choisie par le lanceur.$abr$ WHERE nom = 'Fausses visions' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Fait percevoir à la cible un simple bâton comme un serpent venimeux — illusion totale au toucher, à la vue et à l'odeur — produisant un effet de peur émanant du bâton.$abr$ WHERE nom = 'L''Esprit du Serpent' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Modifie l'apparence du lanceur pour le rendre méconnaissable sans toutefois imiter fidèlement quelqu'un d'autre, le joueur devant porter les changements physiques correspondants.$abr$ WHERE nom = 'Modification d''Apparence' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Fait croire à la ou les cibles que le lanceur est fortuné : chaque écu qu'il leur présente en vaut le triple à leurs yeux.$abr$ WHERE nom = 'Or des Four' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Fait voir à la ou les cibles tout personnage comme un ennemi à attaquer mortellement, jusqu'à ce qu'elles tombent inconscientes ou qu'un sort de calme de niveau supérieur les apaise.$abr$ WHERE nom = 'Rageur Fou' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Donne à la ou les cibles l'apparence de la vie (signes vitaux, corps semblant intact) : simplement vivantes (niv. 1), puis trompant la compétence Diagnostic 1 (niv. 6), Diagnostic 1 et 2 (niv. 11), Diagnostic 1, 2 et 3 (niv. 20).$abr$ WHERE nom = 'Simulacre de vie' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Masque l'aura magique des objets visés : une détection d'aura de niveau inférieur au sort n'y voit aucune aura ; niv. 20 : cache aussi l'aura des artéfacts.$abr$ WHERE nom = 'Aura indétectable' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Permet au lanceur de remplacer des mots de pouvoir de ses formules par n'importe quels mots de la langue commune : 1 (niv. 6), 2 (niv. 10), 3 (niv. 11), 4 (niv. 15), 5 (niv. 20).$abr$ WHERE nom = 'Incantation Fourbe' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Frappe la ou les cibles de peur : incapables d'attaquer ou de viser le lanceur, elles peuvent encore se défendre mais doivent fuir jusqu'à ne plus le voir (un guerrier double son niveau pour résister à la peur).$abr$ WHERE nom = 'Vision Terrifiante' AND cercle = 'Illusion';
UPDATE sorts SET resume_condense = $abr$Confronte la ou les cibles à leur pire peur : faute d'y résister, la cible tombe inconsciente une minute, et si son niveau est inférieur à la moitié du niveau du sort, elle perd tous ses points de vie restants et devient comateuse.$abr$ WHERE nom = 'Assassin Imaginaire' AND cercle = 'Illusion';
