-- Abrégés (resume_condense) — domaine Bénédiction (15 prières) — FICHES Phase 3 s271
-- Idempotent : UPDATE ancré nom+domaine. Rejouable à froid sans effet de bord.

UPDATE prieres SET resume_condense = $abr$Ancre l'âme de la cible dans son corps, la protégeant contre possession, vol d'âme, nécromancie et invocation démoniaque : toute tentative de possession ou de manipulation de l'âme doit dépasser le niveau du sort ; si la cible meurt durant l'effet, son âme reste ancrée (aucune nécromancie de contrôle ou de déplacement possible) et le compte à rebours de la mort est suspendu jusqu'à l'expiration ; sans effet sur un personnage sans âme.$abr$ WHERE nom = 'Ancrage de l''âme' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Érige autour d'une bâtisse fixe et clairement délimitée une barrière invisible qui reconnaît les personnes autorisées et se lie à une origine spirituelle choisie (Tombes, Rêves, Néant ou Cauchemars) : toute entité de cette origine subit 1 dégât magique à chaque tentative de franchissement et ne peut entrer sans invitation explicite — les entités de niveau supérieur au sort forcent le passage mais subissent quand même les dégâts ; une seule zone active au même endroit, le lanceur doit y rester en permanence (sinon fin immédiate) et le sort reste lié au lieu sans se déplacer.$abr$ WHERE nom = 'Bénédiction du Seuil' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Bénit un breuvage tenu en main : chaque gorgée rend des points de vie (1 PV au niv. 6 → 5 PV au niv. 20), une même personne ne pouvant être soignée qu'une fois toutes les 5 minutes (même par un autre prêtre) et plusieurs personnes pouvant boire à la même bouteille ; la boisson ne doit jamais quitter la main du prêtre (posée, donnée ou retirée = fin immédiate) et perd tous ses effets de soin à l'expiration.$abr$ WHERE nom = 'Boisson guérisseuse' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Protège les cibles contre l'application de nouveaux effets de maladie, de poison et de saignement (sans annuler ceux déjà actifs), la couverture s'élargissant par paliers — niv. 6 : saignement et poison mineur ; niv. 10 : maladie mineure ; niv. 12 : poison intermédiaire ; niv. 15 : maladie intermédiaire ; niv. 20 : poison et maladie majeurs.$abr$ WHERE nom = 'Garde de la chair' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Guérit la/les cibles d'une maladie selon le niveau — niv. 1 : mineure ; niv. 6 : intermédiaire ; niv. 11 : majeure ; niv. 20 : toutes les maladies affectant la/les cibles —, le lanceur choisissant la maladie traitée en premier si une cible en porte plusieurs ; celle-ci doit alors attendre un cycle avant d'être guérie d'une autre maladie par ce sort, même lancé par un autre.$abr$ WHERE nom = 'Guérison des Maladies' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Guérit la/les cibles de leurs poisons selon le niveau — niv. 1 : mineur ; niv. 6 : intermédiaire et mineur ; niv. 11 : tous les niveaux (majeur, intermédiaire, mineur), à l'exception du poison mortel.$abr$ WHERE nom = 'Guérison des Poisons' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Immunise les cibles contre les effets d'enchevêtrement, de paralysie, de pétrification et de maladresse de niveau inférieur au sort, empêchant l'application de nouveaux effets concernés sans dissiper ceux déjà en cours ; chaque niveau au-delà du niv. 1 prolonge gratuitement la durée maximale d'une minute (non comptée dans le calcul du sort).$abr$ WHERE nom = 'Liberté de Mouvement' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Génère une lumière magique : certaines créatures de l'ombre peuvent en être affectées et tenteront généralement de la fuir ; le joueur doit fournir sa propre lampe torche à batterie, utilisable pendant la durée, sans jamais la diriger dans les yeux d'une personne pour l'aveugler.$abr$ WHERE nom = 'Lumière' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Substitue le niveau du sort à celui des cibles pour leur faire résister aux effets de capture d'âme.$abr$ WHERE nom = 'Protection de l''Âme' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Ramène à leur forme pure des aliments solides (miche de pain, ragoût, pomme, etc.), les libérant des maladies, poisons ou potions qui les affectaient selon le niveau — niv. 1 : mineurs ; niv. 6 : intermédiaires ; niv. 11 : majeurs.$abr$ WHERE nom = 'Purification de la Nourriture' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Rend aux cibles 1 point de vie par minute jusqu'à un total croissant selon le niveau (2 PV au niv. 6 → 8 PV au niv. 20) ; peut à la place rattacher un membre sectionné de même race (humain à humain, demi-elfe à demi-elfe, chiméride à chiméride), auquel cas le sort ne soigne qu'1 PV sans autre effet — le membre devant être intact, non détruit, frais (moins d'un cycle) et le rattachement se faisant hors combat uniquement.$abr$ WHERE nom = 'Régénération' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Ajoute aux cibles 1 point de guérison lors de l'utilisation de la compétence « Premiers soins » et leur permet de retarder les effets des maladies et des poisons pour la durée ; chaque niveau au-delà du niv. 1 prolonge gratuitement la durée maximale d'une minute (non comptée dans le calcul du sort).$abr$ WHERE nom = 'Renforcement Saint' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Bénit le sang du lanceur contre les créatures des ténèbres : toute créature de niveau inférieur au sort qui tente de se nourrir de son corps par cannibalisme perd les points de vie qu'elle aurait dû regagner ; à partir du niv. 11, chaque effet de drain de vie le ciblant inflige « 1 Dégât » à son auteur (annoncé en le pointant du doigt), quel que soit le niveau de celui-ci.$abr$ WHERE nom = 'Sang Sacré' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Rend des points de vie aux cibles selon le niveau (1 PV au niv. 1 → 6 PV au niv. 20) ; si un rayon est choisi, tous les personnages présents dans la zone sont soignés, ennemis compris ; les soins ne dépassent pas le maximum de la cible et ne restaurent ni points de vie temporaires ni points d'armure.$abr$ WHERE nom = 'Soins' AND domaine = 'Bénédiction';
UPDATE prieres SET resume_condense = $abr$Crée une zone empêchant les personnes contaminées d'y entrer ou d'en sortir (le lanceur choisit au lancement de les garder dedans ou dehors), la contamination bloquée s'étendant par paliers — niv. 6 : parasite ; niv. 11 : maladie mineure ; niv. 15 : maladie intermédiaire ; niv. 20 : maladie majeure.$abr$ WHERE nom = 'Zone Anti-Pathogène' AND domaine = 'Bénédiction';
