-- Traits raciaux : ajout du verbatim manuel (texte_manuel) + exposition dans la vue.
-- Source : manuel_corrige_2026-06-10_phase2_FINAL.txt, section « Description des
-- traits raciaux » (entrées détaillées). Corrections : coquilles/anglicismes
-- (« 1 dégâts » -> « 1 dégât » ; « un 30 secondes consécutif » -> « 30 secondes
-- consécutives »), guillemets typographiques -> droits ; québécismes préservés.
-- `description` reste la version COURTE (fiche courte). Idempotent.

ALTER TABLE public.traits_raciaux
  ADD COLUMN IF NOT EXISTS texte_manuel text;

COMMENT ON COLUMN public.traits_raciaux.texte_manuel IS
  'Verbatim du manuel (entrée détaillée). description = version courte (fiche/glance).';

UPDATE public.traits_raciaux SET texte_manuel = $hv$En utilisant votre langage corporel vous êtes capable de communiquer avec les animaux et certaines créatures non-verbales. Cette compétence ne vous permet pas de poser des questions, mais vous pourrez comprendre si une créature est effrayée, heureuse, ou d'autres interactions du genre. Dans le même genre, vous pouvez indiquer votre territoire et tenter d'effrayer certaines créatures. Cette compétence ne s'utilise pas en combat. Lorsque vous l'utilisez, annoncez le poing levé à ceux concernés que vous possédez la compétence.$hv$ WHERE id = '44c97fb5-deba-4879-8cda-2bedc4dc3382';  -- Affinité animale
UPDATE public.traits_raciaux SET texte_manuel = $hv$Les gobelins ne sont ni les plus grands ni les plus forts, mais ils savent comment gagner du temps quand il s'agit de prendre la fuite. 1 fois par cycle, si vous voulez fuir un adversaire, vous pouvez lui asséner un coup bien placé sur le pied en annonçant "Casse-pied". Pour jouer cette action, donnez simplement un coup au sol proche des pieds de votre cible. Votre cible doit s'arrêter pendant 5 secondes à cause de la douleur, vous laissant une précieuse avance. Cette compétence ne fonctionne pas en plein combat, seulement lors d'une tentative de fuite.$hv$ WHERE id = '7bfb8e13-2466-48d3-8ad1-a2aba76949fa';  -- Casse-pied
UPDATE public.traits_raciaux SET texte_manuel = $hv$Cette compétence permet à un personnage de se soigner en mangeant la chair crue d'un corps frais (décédé durant le même cycle) ou même d'un être vivant. L'action de consommation doit être accompagnée d'actions claires et bruyantes pendant 2 minutes complètes alors que le personnage dévore une partie d'un corps. Si le corps de la cible qu'il dévore est affecté d'un poison, le cannibale sera également affecté par celui-ci. Cette compétence redonne 1 point de vie en 2 minutes. Cette compétence peut être utilisée pour soigner jusqu'à un maximum de 5 points de vie par cycle. Si vous mangez la chair d'un être vivant, l'action de consommation inflige 1 dégât par minute. Cette action ne s'utilise pas en combat.$hv$ WHERE id = '1db17667-e112-451e-b691-e53b0daf3970';  -- Charognard
UPDATE public.traits_raciaux SET texte_manuel = $hv$Cette compétence vous permet de re-piger une seule carte lors de la collecte de plantes ou de minerais. La 2e pige devient celle valide.$hv$ WHERE id = '4675941e-481c-410d-a14f-9c2672d219ba';  -- Coup du destin
UPDATE public.traits_raciaux SET texte_manuel = $hv$En tant que créature des tréfonds, vous préférez clairement la nuit au jour. De nuit, vous avez +1 point de vie.$hv$ WHERE id = '20d1ccad-2446-406e-a111-9a75cb8777df';  -- Créature des ténèbres
UPDATE public.traits_raciaux SET texte_manuel = $hv$Cette compétence permet à votre personnage d'ingérer un nombre de potions égal à son nombre total de points de vie par cycle au lieu du 50% régulier.$hv$ WHERE id = 'c9e21d23-34b1-40fb-8860-357b89a17358';  -- Estomac d'acier
UPDATE public.traits_raciaux SET texte_manuel = $hv$Grâce à leur odorat supérieur, les Chimérides peuvent traquer leur proie avec une précision inégalée. Cette capacité leur permet de suivre une cible à l'odeur, peu importe qu'elle vole ou qu'elle change d'apparence. La cible doit avoir été présente dans les 12 dernières heures et vous devez avoir un échantillon de son odeur (un objet qui lui appartient, ou un endroit où il s'est assis longtemps, un écu qu'il a donné à quelqu'un, etc.). Plus l'objet portera une odeur forte, plus la traque sera précise. Certains facteurs (pluie, feu, fortes odeurs) peuvent perturber ou interrompre la traque. Cette compétence est principalement utilisée pour retrouver des Personnages Non-Joueur (PNJ). Si la cible est en jeu, un maître de jeu le guidera dans la poursuite. Notez que si vous cherchez un joueur, il est fort possible que le maître de jeu ne sache pas où il se trouve malheureusement et ne pourra pas vous aider.$hv$ WHERE id = '98f20cb6-6978-414b-bfe8-34bafe81d175';  -- Flair affûté
UPDATE public.traits_raciaux SET texte_manuel = $hv$Votre personnage a l'œil pour les détails qui échappent aux autres et le flair pour être au bon endroit au bon moment. Qu'il s'agisse de providence divine, d'un sens de l'observation exceptionnel ou d'un animal de compagnie qui cherche pour vous, vous parvenez toujours à dénicher quelque chose d'utile. Cette capacité vous permet de bénéficier de 1 action de votre choix parmi la liste. Les actions doivent être spécifiées lors de l'inscription, avant le début du jeu avec un maître de jeu.
1- Vous trouvez de la monnaie. Au hasard : un écu ou une pierre précieuse. (valeur max 20 écus)
2- Vous trouvez une pépite de minerai commun spécifique avec 50% de chance de succès, sinon vous aurez une pépite de minerai commun au hasard.
3- Vous trouvez une plante commune spécifique avec 50% de chance de succès, sinon vous aurez une plante commune au hasard.
4- Vous trouvez de l'information sur quelque chose qui se produit dans les alentours comme un animal étrange, une attaque dans les bois, des déplacements inusités, et d'autres informations de ce genre.$hv$ WHERE id = 'fad7ba5d-df90-4f24-88b4-987eb9a4891f';  -- Fortuné
UPDATE public.traits_raciaux SET texte_manuel = $hv$L'inaptitude magique des orcs vous a été transmise génétiquement. Vous ne pourrez jamais avoir de points de spiritualité. Les points de spiritualité que vous auriez de base en créant votre personnage n'existent plus et vous ne pourrez jamais en acheter. En échange vous avez 1 point de vie supplémentaire.$hv$ WHERE id = '160abee1-2096-456a-8578-4ab8438bfaba';  -- Inapte à la magie
UPDATE public.traits_raciaux SET texte_manuel = $hv$En tant que maître alchimiste qui boit ses potions depuis plusieurs années, le gobelin se retrouve maintenant infusé lui-même d'ingrédients. Le personnage reconnaît les propriétés magiques de sa propre salive. 1 fois par événement, votre personnage peut remplacer 1 dose alchimique de potion ou poison mineur par sa salive, à l'exception du catalyseur. N'utilisez pas votre vraie salive. Remplacez-la par de l'eau. Vous devrez suivre les mêmes manipulations alchimiques que l'ingrédient original que vous remplacez. Cette dose peut être mise en fiole mais n'aura qu'une durée de vie d'un cycle.$hv$ WHERE id = 'a3039c0b-525d-4282-a92b-09d939b801f2';  -- Infusé
UPDATE public.traits_raciaux SET texte_manuel = $hv$En tant que créature de proie, vous avez développé des réflexes aiguisés contre les attaques surprises. 1 fois par événement seulement, si vous êtes la cible de la compétence Assommer, vous pouvez dire à la personne qui vous attaque que vous évitez le coup au dernier moment grâce à ce trait racial. Vous devrez jouer la surprise tout de même, mais vous ne perdrez pas connaissance.$hv$ WHERE id = '371f712e-83b0-4684-b65f-9cb6113c915b';  -- Instinct de survie
UPDATE public.traits_raciaux SET texte_manuel = $hv$Votre présence imposante et votre ton direct vous donnent un avantage dans les négociations. Lors d'un échange commercial, vous pouvez imposer un "Dernier Prix" qui force votre interlocuteur à descendre son prix au plus bas possible. Vous ne pouvez pas forcer un marchand à vendre à perte, mais il peut accepter de ne faire aucun profit. De plus, si un échange devient houleux, vous pouvez déclencher une épreuve de volonté où chacun fixe l'autre dans les yeux sans cligner : le premier qui détourne le regard doit céder un peu sur son prix. Ce trait racial s'utilise 1 fois par événement.$hv$ WHERE id = 'b6e46414-4a68-4cc0-a3f0-3d223c1c9f67';  -- Marchandage Musclé
UPDATE public.traits_raciaux SET texte_manuel = $hv$Votre héritage mixte vous a appris à naviguer entre les attentes et les préjugés, faisant de vous un expert de la dissimulation. Votre personnage peut résister à un effet de vérité par événement. Que ce soit un sort ou une potion. Le premier effet reçu durant l'événement est celui auquel vous résistez. Le joueur qui possède cette compétence n'est pas obligé de dire "résiste" ni de mentionner aux autres joueurs qu'il possède la capacité de mentir. Ce trait racial ne protège pas contre la compétence Torture ni Hypnose.$hv$ WHERE id = 'a61750bc-a82b-44b9-8d79-3594b42e40fa';  -- Mythomane
UPDATE public.traits_raciaux SET texte_manuel = $hv$L'essence magique du monde coule différemment dans vos veines. En canalisant votre magie à travers vos mains, vous êtes capable d'infliger une douleur intense à une cible. Cette cible doit être vivante et faite de chair. Lorsque vous agrippez un adversaire à peau nue, celui-ci ressent une sensation de brûlure insoutenable. Si vous maintenez la prise pendant 30 secondes consécutives, la cible perd 1 point de vie, et vous devez dépenser 1 point de spiritualité. Vous pouvez seulement dépenser 1 point de spiritualité lorsque vous faites cette action. Cette blessure laisse une marque de main là où elle a été faite, mais des soins peuvent l'effacer. Cette compétence ne peut pas être utilisée avec des gants ou sur une armure. Cette compétence s'utilise 1 fois par cycle.$hv$ WHERE id = 'cbf32861-e0ea-49e8-b315-568588569fa8';  -- Poigne ardente
UPDATE public.traits_raciaux SET texte_manuel = $hv$En raison de leur longue barbe et leur travail dans les mines, les Myrvalks accumulent une poussière métallique étrange dans leurs poils. Une fois par événement, un(e) Myrvalk peut secouer sa barbe et récupérer une pincée de cette poussière, qui une fois tapée ensemble, donne une pépite de minerai commun au hasard.$hv$ WHERE id = 'c36596fb-6d6e-490f-8886-3e0d08c5c099';  -- Poussière des profondeurs
UPDATE public.traits_raciaux SET texte_manuel = $hv$Parce que rien ne vaut une bonne bière pour se remettre sur pieds. Un(e) Myrvalk soigné(e) par la compétence Premiers Soins peut améliorer son efficacité en buvant un breuvage alcoolisé durant la guérison, lui offrant un point de vie supplémentaire. La boisson doit être consommée durant les soins. Limite de 1 boisson par premier soin. Cette compétence ne fonctionne que si le soin est effectué correctement et hors-combat. Si jamais vous n'êtes pas un buveur d'alcool dans la vraie vie, ou que vous êtes un mineur, vous pouvez jouer que votre personnage boit de l'alcool alors que vous buvez de l'eau. Jouer l'effet de l'alcool par la suite.$hv$ WHERE id = 'a5973fb1-8c4b-42e2-8184-f949a4982345';  -- Remède des Braves
UPDATE public.traits_raciaux SET texte_manuel = $hv$Votre héritage génétique, ou votre foie endurci, vous donne une résistance au poison. 1 fois par événement, si votre personnage est la cible d'un poison mineur, il lui résiste automatiquement. Par contre, s'il est la cible d'un poison intermédiaire ou majeur et qu'il a besoin d'un antidote pour se soigner, il n'aura besoin que d'un antidote mineur pour soigner un poison intermédiaire et un antidote intermédiaire pour soigner un poison majeur. Le premier poison reçu durant l'événement est celui qui sera résisté ou réduit, les autres poisons subséquents auront leur plein potentiel.$hv$ WHERE id = '01302682-1182-4bf8-85a7-a91f87817101';  -- Résistance aux poisons
UPDATE public.traits_raciaux SET texte_manuel = $hv$Grâce à votre connexion ancestrale à la magie vous êtes capable de détecter si un objet est magique, mais vous êtes incapable d'identifier ses effets, ni son niveau de puissance. Vous pouvez aussi savoir si l'objet est enchanté, si un sort temporaire masque sa nature magique ou si un sort donne une illusion d'enchantement. Afin d'utiliser cette compétence, vous devrez toucher l'objet pendant 30 secondes et vous concentrer dessus. Cette action peut être utilisée seulement 1 fois par cycle.$hv$ WHERE id = 'e550c444-7e31-4abe-a35e-95297afa3e4e';  -- Résonance magique
UPDATE public.traits_raciaux SET texte_manuel = $hv$Votre ancêtre elfique est un peu plus proche de vous que la majorité de la population demi-elfe. Cela vous donne une résistance plus élevée aux effets de charmes. Vous pouvez résister à 1 sort du cercle de Charme par événement. (Amitié, Antipathie, Avidité, Discours captivant, Domination Universelle, Envoûtement, Esprit du Simplet, Fou Rire Incessant, Mensonge, Oubli, Suggestion) Le premier sort reçu de ce cercle durant l'événement est celui auquel vous résisterez.$hv$ WHERE id = 'f02c7c2a-a18c-4670-8781-6d45121591e3';  -- Sang féerique
UPDATE public.traits_raciaux SET texte_manuel = $hv$Ayant grandi dans les tréfonds de l'Ombre-Terre, votre sang porte encore les essences sombres de ce lieu. 1 fois par événement, en effectuant une saignée de 2 minutes, votre personnage est capable de mettre en fiole son sang au potentiel douloureux. Cette fiole de sang est l'équivalent du poison "Poison de douleur" et la fiole est bonne pour 1 cycle.$hv$ WHERE id = 'f82081ce-764b-4e2b-9b20-e497801a8fa1';  -- Sang toxique

CREATE OR REPLACE VIEW public.vue_traits_par_race AS
 SELECT rt.id AS race_trait_id,
    rt.race_id,
    rt.trait_id,
    rt.sous_type,
    r.nom AS race_nom,
    tr.nom AS trait_nom,
    tr.description AS trait_description,
    tr.cout_xp,
    tr.est_actif,
    tr.texte_manuel AS trait_texte_manuel
   FROM race_traits rt
     JOIN races r ON r.id = rt.race_id
     JOIN traits_raciaux tr ON tr.id = rt.trait_id
  WHERE tr.est_actif = true
  ORDER BY r.nom, rt.sous_type, tr.nom;
