-- Morceau A : verbatim manuel des 15 assemblages de runes
-- Ajoute la colonne texte_manuel + remplit les 15 + corrige coquille Notogh->Nothogh
-- Idempotent : ADD COLUMN IF NOT EXISTS + UPDATE par nom + replace() ciblé

ALTER TABLE public.assemblages_runes ADD COLUMN IF NOT EXISTS texte_manuel text;

UPDATE public.assemblages_runes SET texte_manuel = $vm$Cette combinaison de runes a été souvent utilisée pendant les périodes de guerre et lors des expéditions visant à accroître le réseau minier des nains. L'enchantement de ces runes offre une endurance nouvelle aux individus qui les portent, plus résistants et plus robustes. Une fois activé, l'assemblage offre 1 point de vie temporaire supplémentaire à son porteur pour une durée d'une heure. Ce point de vie peut être guéri normalement pour toute la durée de l'effet. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, il peut augmenter sa puissance pour choisir 3 cibles en consumant 7 points de spiritualités pour une durée d'une heure également.$vm$ WHERE nom = 'Assemblage de résilience';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Populaire parmi les forgerons ainsi que les marchands d'armures de seconde main. Une fois activé, l'assemblage offre 1 point d'armure supplémentaire à l'armure pour une durée de 2 heures. Ce point d'armure peut être réparé normalement pour toute la durée de l'effet. Une fois l'effet terminé, le point d'armure obtenu par l'assemblage disparaît. Cet assemblage, une fois dessiné, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour rendre son armure très résistante lui offrant 3 points d'armures pour 1 heure.$vm$ WHERE nom = 'Assemblage de rigidité';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Cet assemblage est principalement utilisé par les constructeurs nains comme symbole de protection dans le but de protéger leurs structures. Il devient aussi un allié utile des forgerons qui les gravent sur les armures qu'ils produisent. Cet assemblage, une fois activé, augmente le nombre de combats maximal de l'armure de 1. Cet effet dure pendant un cycle. Une fois l'enchantement terminé, l'armure coûte deux pépites supplémentaires de chaque matériau lors de sa prochaine réparation. Cet assemblage, une fois dessiné, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 8 points de spiritualités pour donner à son armure une régénération naturelle, Elle se répare donc seule si elle est brisée après un combat ramenant son nombre de combat a 0. Cet effet dure pendant 1 cycle.$vm$ WHERE nom = 'Assemblage du bâtisseur';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Ce cumulatif de runes est posé sur le front des décédés, leur assurant un passage digne et sans embûches. Ses bénéfices s'étendent aussi aux vivants, capables de restreindre l'emprise malveillante de la mort. Une fois cet assemblage activé, le personnage ne peut plus être transformé en mort-vivant pour une durée d'une heure. Elle ne protège pas contre la possession. Cet assemblage, une fois dessiné, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour offrir un repos divin à la cible qui est protégé de toute possession. Les tentatives sont punis par un 3 dégâts bénie au lanceur de sort qui s'attaquerait au mort. De plus, le sang du mort est béni. L'effet de cette rune dure pendant 1 heure.$vm$ WHERE nom = 'Assemblage de repos en paix';

UPDATE public.assemblages_runes SET texte_manuel = $vm$De nombreuses expéditions ont été entreprises dû à l'usage de ces runes. Un grand nombre de nains intrépides jure la réussite de leurs missions à l'étranger que par les bénéfices de ces runes. Lorsqu'il est activé, cet assemblage donne au joueur une réduction de dommage de 1 sur les dégâts de feu, glace, acide, électricité ou de vent qu'il reçoit. Cette protection reste active pendant 1 heure. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 9 points de spiritualités pour se créer un bouclier élémentaire de 3 de réduction de dommage contre chaque type de dégâts (de glace, feu, acide, foudre et vent) durant une heure.$vm$ WHERE nom = 'Assemblage de protection contre les éléments';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Longtemps utilisé par les explorateurs de région sauvage et par les marchands de grand chemin. Cet assemblage, lorsqu'il est activé, protège contre les effets de paralysie ou d'enchevêtrement qui peuvent affecter son porteur pour une durée de 30 minutes. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour immunisé 4 autres cibles aux effets contraignants durant 30 minutes$vm$ WHERE nom = 'Assemblage de liberté';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Utilisée largement comme bénédiction sur les instruments de minage des peuples nains, cette rune sert à trouver sa voie dans le domaine de la guerre rapidement. Lorsque cet assemblage est activé, le bouclier ou l'arme qui le porte devient indestructible pour une durée de 30 minutes. Cet assemblage, une fois dessiné, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour rendre son bouclier tellement fort qu'il permet de faire un désengagement (repoussé 1 mètre) en plus de rendre son arme indestructible. Cet assemblage dure 30 minutes et un seul désengagement est possible par assemblage de durabilité activé.$vm$ WHERE nom = 'Assemblage de durabilité';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Cette combinaison de runes a été découverte par accident tentant de renforcer des outils de forge il a plutôt eu pour résultat de doubler l'efficacité de chaque coup. Cet assemblage peut être fait sur un marteau de forge ou une enclume. Une fois activé, tous les temps de production, de réparation ou de renforcement sont réduits de moitié si le forgeron utilise l'objet porteur de l'assemblage. Cet effet dure 1 heure. Cet assemblage, une fois dessiné, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualité pour sauver des coûts en matériaux. Utilisant le meilleur potentiel possible pour ses minerais durant 1 heure. Lorsque le forgeron utilise 4 barres et plus dans l'heure, il sauve une barre du métal le plus présent dans le ou les objets forgés.$vm$ WHERE nom = 'Assemblage de productivité';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Privilégié pour ses capacités à renforcer l'endurance mentale de son porteur, cet assemblage a souvent été associé à la détermination. Cet assemblage, une fois activé, offre à son porteur un bonus de 2 niveaux supplémentaire pour résister aux sorts. Cet effet dure 30 minutes. Une fois activé, il consume 5 points de spiritualités au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour gagner également 4 niveaux de résistance magique a 2 autres cibles durant 30 minutes.$vm$ WHERE nom = 'Assemblage de barrière magique';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Cet assemblage fut des plus utiles durant la guerre de Heimrook. Laissant les prêtres nains obtenir de l'information cruciale aux combats qui en ont découlé. Cet assemblage, une fois activé, permet aux porteurs de passer dans l'univers éthéré devenant intangibles. L'effet dure 1 minute. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour être intangible pendant 5 minutes et il peut envoyer un Pieu spirituel pour rendre une cible intangible tangible pour une durée de 5 minutes. Le Pieu spirituel est un sort à effet égal au niveau du joueur qui possède la rune.$vm$ WHERE nom = 'Assemblage du passage';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Vastement utilisé sur tous blessés ou malades lorsqu'un connaisseur des runes est présent. Plusieurs ont voué leur retour sur pied à cet assemblage. Une fois activé, le porteur de cet assemblage gagne toujours un point de vie supplémentaire lorsqu'il reçoit des guérisons. Cet assemblage dure 1 heure. Cet assemblage, une fois activé, consume 5 points de spiritualité au porteur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour arrêter temporairement toute maladie et poison, ainsi que de faire repousser un membre manquant. Durée d'une heure.$vm$ WHERE nom = 'Assemblage de régénération';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Les textes originaux décrivent cet assemblage porté par les prêtres guérisseurs leur permettant de guérir des patients hautement contagieux voire toxiques. Cet assemblage de runes, une fois activé, protège son porteur contre un poison ou une maladie de niveau mineur ou intermédiaire. Cet effet reste actif pour une durée de 1 heure complète, mais se dissipe après avoir résisté au prochain poison ou à la prochaine maladie. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour résister au prochain poison ou maladie mortelle. Cet effet reste actif pour une durée de 1 heure complète, mais se dissipe après avoir résisté.$vm$ WHERE nom = 'Assemblage de santé';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Bien que la création de cet assemblage fut nécessaire durant la guerre d'Heimrook, le reste des prêtres nains aurait préféré ne jamais avoir eu à expérimenter pour découvrir cet assemblage. Malgré ce mal nécessaire, il fut un instrument majeur dans la victoire du peuple nain. Cet assemblage, une fois activé, donne +2 sur le niveau du personnage lorsqu'il tente de résister à un sort du cercle de magie noire (possédant le mot de pouvoir "Nothogh") et du cercle de la nécromancie (possédant le mot de pouvoir "Thork"). De plus, il a aussi un résistance de dégât de ces cercles de 1(drain-life, énergie négative). Cet effet dure 1 heure. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualités pour avoir une résistance plus forte aux dégâts (2 de résistance au lieu de 1) de ces deux cercles ainsi qu'un immunité à la capture d'âme en plus de garder les effets de l'assemblage de base (+2 contre les sort à effet). Cet effet dure 1 heure.$vm$ WHERE nom = 'Assemblage de protection du mal';

UPDATE public.assemblages_runes SET texte_manuel = $vm$L'empire nain, bien que brave et courageux a vu des périodes de conflits internes parfois mortels. Un dirigeant important serait à l'origine de cet assemblage craignant sa mort aux mains de son frère. Cet assemblage, une fois tracé, protège son porteur contre le prochain coup de grâce qu'il pourrait recevoir durant les deux prochaines heures. Dès qu'il annule un coup de grâce, l'effet se termine automatiquement et ne protège donc plus son porteur. Un personnage étant protégé de cette façon reste inconscient pendant la durée complète de son 10 minutes. Les guérisons, même magiques, ne peuvent pas le guérir. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualité pour revenir à deux points de vie et créer une zone de sanctuaire égal à son niveau de joueur à 10 pieds autour de lui durant 5 minutes. Le lanceur du sort génère une force autour de sa personne capable d'empêcher les autres personnages de s'approcher de lui à moins de 10 pieds. Il peut choisir de laisser entrer et sortir d'autres personnages de son choix. Le prêtre ne peut pas se déplacer sous peine de terminer le sort immédiatement.$vm$ WHERE nom = 'Assemblage de préservation';

UPDATE public.assemblages_runes SET texte_manuel = $vm$Bien que la recherche de minerais et de gemmes fut le premier amour du peuple nain, leur curiosité pour les objets enchantés les a encouragés à devenir créatifs. Un fameux et très rare magicien nain serait le concepteur de cet assemblage. Il fut utilisé par plusieurs marchands de grand chemin. Cet assemblage, une fois activé, permet au personnage de voir les auras magiques des objets qu'il touche comme un sort à effet égal à son niveau. (ceci est juste une détection de la magie, cela ne permet pas de connaître l'objet). Il obtient +2 de résistance contre les sorts à effet de l'école de l'illusion (possédant le mot de pouvoir "Guerben"). Cet assemblage dure 1 heure. Cet assemblage, une fois activé, consume 5 points de spiritualité au traceur. S'il possède la maîtrise des assemblages, le Marqueur peut consumer 7 points de spiritualité pour augmenter la résistance a +5 et lui permettre de connaître la nature d'un objet magique en le touchant tout cela sur une durée d'une heure comme un sort à effet égal à son niveau.$vm$ WHERE nom = 'Assemblage de vision pure';

-- Correction coquille : champ structuré description_longue de 'protection du mal' (Notogh -> Nothogh)
UPDATE public.assemblages_runes
  SET description_longue = replace(description_longue, 'Notogh', 'Nothogh')
  WHERE nom = 'Assemblage de protection du mal' AND description_longue LIKE '%Notogh%';
