-- Abrégés (resume_condense) des cercles Terre, Feu et Eau — 31 sorts (FICHES Phase 3, s269)
-- Idempotent : UPDATE ancré sur nom + cercle (rejouable à froid → même état). Champs resume_condense vides au départ = ajout pur, aucun intégral (description) touché.

-- ===== TERRE (10) =====
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles un bouclier absorbant un nombre de dégâts d'acide égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Bouclier de Terre' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Emprisonne la ou les cibles des pieds aux genoux dans une terre magique qui se reforme même frappée ou creusée : impossibles à déplacer, elles peuvent encore attaquer, se défendre et incanter sur place.$abr$ WHERE nom = 'Emprisonnement dans la Terre' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Encaisse sans dégât un nombre de coups d'armes conventionnelles non magiques selon le niveau — 1 (niv. 1), 2 (niv. 5), 3 (niv. 6), 4 (niv. 11), 5 (niv. 20) — les coups assommants comptant comme un coup normal ; protège aussi contre la prochaine attaque sournoise mais consomme alors toutes les protections restantes, et bloque la pétrification de niveau inférieur (la cible annonce « résiste »).$abr$ WHERE nom = 'Peau de Pierre' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Pétrifie la ou les cibles : immobiles, muettes et impossibles à déplacer ou à blesser, elles voient, sentent et entendent encore ; sert aussi à dépétrifier, à condition que la pétrification d'origine soit de niveau inférieur.$abr$ WHERE nom = 'Pétrification/Dépétrification' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts d'acide croissant avec le niveau : 1 au niveau 1, jusqu'à 8 au niveau 20.$abr$ WHERE nom = 'Rayon d''Acide' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Fait tomber au sol les personnages de la zone (jamais le lanceur) ; niv. 11 : inflige aussi 1 dégât à chaque cible, porté à 2 au niv. 20.$abr$ WHERE nom = 'Tremblement de Terre' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Permet à la ou les cibles de manier des armes à deux mains même sans la compétence d'armes pour la durée ; niv. 11 : elles ne peuvent plus être désarmées.$abr$ WHERE nom = 'Poigne de fer' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Quand la cible tombe à 0 point de vie, la met automatiquement en régénération au sol (1 PV par minute pendant 5 minutes tant qu'elle y reste) et lui rend conscience après 5 minutes au lieu de 10, toujours sans souvenir ; fonctionne seulement à l'extérieur (le corps doit toucher la terre) et se réactive si elle retombe à 0 pendant la durée.$abr$ WHERE nom = 'Sang de la Terre' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Au toucher, inflige des dégâts d'acide selon le niveau, +1 si la cible porte une armure : 4 (niv. 6), 5 (niv. 10) ; aux niveaux 11 et 20, soit deux cibles à 4/5 dégâts chacune, soit une seule à 7/10.$abr$ WHERE nom = 'Toucher Corrosif' AND cercle = 'Terre';
UPDATE sorts SET resume_condense = $abr$Couvre une zone d'une pluie corrosive : toute créature vivante présente ou qui y entre subit des dégâts d'acide aussitôt puis chaque minute tant qu'elle reste (+1 si elle porte une armure physique), le lanceur — jamais affecté — devant rester conscient et dans la zone sous peine d'interrompre le sort ; dégâts selon le niveau : 1 (niv. 11), 2 (niv. 15, dåtruit le cuir), 3 (niv. 18, détruit la maille), 4 (niv. 20, détruit la plaque et épargne les alliés).$abr$ WHERE nom = 'Pluie acide' AND cercle = 'Terre';

-- ===== FEU (10) =====
UPDATE sorts SET resume_condense = $abr$Rend la ou les cibles intensément assoiffées : elles doivent faire de la recherche d'eau potable leur priorité, tout en pouvant encore se défendre.$abr$ WHERE nom = 'Assoiffé' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Conféré a la ou les cibles un bouclier absorbant un nombre de dégâts de feu égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Bouclier de Feu' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts de feu croissant avec le niveau : 1 au niveau 1, jusqu'à 8 au niveau 20.$abr$ WHERE nom = 'Jet de flammes' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Génère une lumière magique (le joueur utilise sa propre lampe torche pour la durée) que certaines créatures de l'ombre cherchent à fuir ; interdit de la diriger dans les yeux pour aveugler.$abr$ WHERE nom = 'Lumière' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Impose aux cibles de la zone d'agir comme si l'air ambiant était à 60 °C, une chaleur qui empêche toute concentration et donc tout sort ou prière.$abr$ WHERE nom = 'Réchauffement de Température' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Si le lanceur tombe à 0 point de vie pendant la durée, déclenche une explosion de feu autour de lui infligeant des dégâts aux créatures et personnages proches (jamais au lanceur) selon le niveau : 2 dégâts sur 5 pieds (niv. 6), 3 sur 10 (niv. 10), 4 sur 15 (niv. 15), 5 sur 20 (niv. 20) ; une seule fois par lancement, et pas s'il se met volontairement à 0.$abr$ WHERE nom = 'Brasier Vengeur' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Chauffe à blanc des objets en måtal, qui deviennent impossibles à tenir pour la durée — affecté d'office si l'objet n'est pas porté, sinon le niveau du sort s'oppose à celui du porteur ; niv. 11 : si la cible ne peut retirer l'objet bloqué (armure ou bouclier), elle subit 1 dégât de feu au début puis 1 par minute tant qu'il reste sur elle, dégâts cessant dès qu'il est retiré ou le sort terminé.$abr$ WHERE nom = 'Réchauffement du Métal' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Entoure la ou les cibles d'une aura qui renvoie des dégâts de feu à tout attaquant au corps à corps (attaque physique ou sort/prière au toucher), sans empêcher la cible de subir le coup et à annoncer par elle — sans effet sur les attaques à distance ; dégâts renvoyés : 1 (niv. 6), 2 (niv. 11), 3 (niv. 20).$abr$ WHERE nom = 'Retour de flamme' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Au toucher, inflige des dégâts de feu selon le niveau : 5 (niv. 6), 6 (niv. 10) ; aux niveaux 15 et 20, soit deux cibles à 5/6 dégâts chacune, soit une seule à 8/10.$abr$ WHERE nom = 'Toucher de Braise' AND cercle = 'Feu';
UPDATE sorts SET resume_condense = $abr$Enflamme la cible (état Enflammé), qui doit aussitôt consacrer une action claire à s'éteindre sous peine de perdre 50 % de ses points de vie totaux (armure comprise) ; une même cible ne peut être touchée qu'une fois par combat.$abr$ WHERE nom = 'Brasero' AND cercle = 'Feu';

-- ===== EAU (11) =====
UPDATE sorts SET resume_condense = $abr$Impose aux cibles de la zone d'agir comme si l'air ambiant était à −40 °C, un froid qui empêche toute concentration et donc tout sort ou compétence.$abr$ WHERE nom = 'Abaissement de Température' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Confère à la ou les cibles un bouclier absorbant un nombre de dégâts de glace égal à la moitié du niveau du sort (arrondi à l'unité supérieure).$abr$ WHERE nom = 'Bouclier de Glace' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Immunise la ou les cibles contre les nouveaux poisons reçus pendant la durée — sans annuler ceux déjà actifs — d'abord mineurs, puis intermédiaires (niv. 6), majeurs sauf le mortel (niv. 11), et au niv. 20 majeurs plus le coup de grâce du poison mortel, qui ne fait alors que rendre comateux à 0 point de vie.$abr$ WHERE nom = 'Immunité au Poison' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Inflige des dégâts de glace croissant avec le niveau : 1 au niveau 1, jusqu'à 8 au niveau 20.$abr$ WHERE nom = 'Projectile de glace' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Purifie les liquides visés non encore consommés en les débarrassant de toute maladie, potion ou poison qu'ils contiennent — d'intensité mineure, puis intermédiaire (niv. 6) et majeure (niv. 11).$abr$ WHERE nom = 'Purification des Liquides' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Gèle des objets en métal, qui deviennent impossibles à tenir pour la durée — affecté d'office si l'objet n'est pas porté, sinon le niveau du sort s'oppose à celui du porteur ; niv. 11 : si la cible ne peut retirer l'objet bloqué (armure ou bouclier), elle subit 1 dégât de glace au début puis 1 par minute tant qu'il reste sur elle, dégâts cessant dès qu'il est retiré ou le sort terminé.$abr$ WHERE nom = 'Froid Glacial' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Transforme la ou les cibles en statue de glace : immobiles, muettes et incapables de bouger, elles voient, sentent et entendent encore mais ne peuvent subir aucun dégât ; cet effet ne compte pas comme de la pétrification.$abr$ WHERE nom = 'Iceberg' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Donne à la ou les cibles l'impression de se noyer : à genoux ou au sol, elles suffoquent et ne peuvent ni parler, ni incanter, ni attaquer, ni utiliser de compétences pour la durée — seul un déplacement lent reste possible.$abr$ WHERE nom = 'Noyade' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Ronge de rouille le ou les objets métalliques visés — affecté d'office s'il n'est pas porté, sinon le niveau du sort s'oppose à celui du porteur, et un objet magique résiste sauf au niv. 20 ; une arme måtallique devient fragile (détruite au prochain dégât qu'elle inflige) et une armure perd des combats à son total restant : 1 (niv. 6), 2 (niv. 10), 3 (niv. 11), 4 (niv. 20, qui atteint aussi les objets magiques sauf les artéfacts).$abr$ WHERE nom = 'Rouille' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Au toucher, inflige des dégâts de glace selon le niveau : 4 (niv. 6), 5 (niv. 10) ; aux niveaux 11 et 20, soit deux cibles à 4/5 dégâts chacune, soit une seule ç 7/10.$abr$ WHERE nom = 'Toucher Glacial' AND cercle = 'Eau';
UPDATE sorts SET resume_condense = $abr$Confère à la cible — qui ne doit porter aucune armure physique — des points d'armure de givre temporaires égaux à la moitié du niveau (arrondi à l'unité supérieure), non récupérables une fois perdus, en la rendant vulnérable à la chaleur (+1 dégât de feu subi) ; niv. 15 : tout attaquant au corps à corps subit 2 dégâts de glace par coup réussi, effet cessant si l'armure de givre tombe è 0 ; niv. 20 : chaque dégât de glace reóu rend 1 point d'armure (sans dépasser le maximum initial, et pas si l'armure a été entaièrement détruite).$abr$ WHERE nom = 'Armure Givre' AND cercle = 'Eau';