-- Migration B3 : description_courte (mode Fiche) pour la table prieres.
-- Scope strict : table prieres. Ne touche pas description (verbatim), ni vues, ni types.ts.
-- Matching (domaine, nom). Idempotent : ADD COLUMN IF NOT EXISTS + IS DISTINCT FROM.

ALTER TABLE prieres ADD COLUMN IF NOT EXISTS description_courte text;

UPDATE prieres AS p
SET description_courte = v.courte
FROM (VALUES
  ('Bénédiction','Guérison des Maladies','Guérit une maladie de la cible (1 à la fois, délai d''1 cycle entre 2 soins). Gravité soignée ↑ avec le niveau : mineure → toutes.'),
  ('Bénédiction','Guérison des Poisons','Guérit les poisons de la cible. Niveau soigné ↑ avec le niveau (mineur → majeur) ; jamais le poison mortel.'),
  ('Bénédiction','Liberté de Mouvement','Immunise les cibles contre enchevêtrement, paralysie, pétrification et maladresse de niveau inférieur. Ne dissipe pas les effets en cours.'),
  ('Bénédiction','Lumière','Génère une lumière magique (lampe torche du joueur) ; fait fuir certaines créatures de l''ombre. Interdit d''aveugler quelqu''un.'),
  ('Bénédiction','Protection de l''Âme','Les cibles résistent à la capture d''âme avec le niveau du sort au lieu du leur.'),
  ('Bénédiction','Purification de la Nourriture','Purifie un aliment solide ; retire la maladie, le poison ou la potion qui l''affecte. Gravité retirée ↑ avec le niveau.'),
  ('Bénédiction','Renforcement Saint','Cibles : +1 soin via Premiers soins, et peuvent retarder les effets de maladies/poisons pendant la durée.'),
  ('Bénédiction','Soins','Rend des PV (1 → 6 selon le niveau ; jamais au-delà du max, ni PV temporaires/armure). En rayon, soigne aussi les ennemis présents.'),
  ('Bénédiction','Boisson guérisseuse','Bénit un breuvage tenu en main (fin si lâché). Chaque gorgée rend 1 → 5 PV selon le niveau ; 1 fois / 5 min par personne.'),
  ('Bénédiction','Garde de la chair','Protège contre les nouveaux effets de saignement, poison et maladie (n''annule pas ceux en cours). Couverture ↑ avec le niveau.'),
  ('Bénédiction','Régénération','Rend 1 PV/min jusqu''à un total de 2 → 8 PV selon le niveau. Peut à la place rattacher un membre sectionné (frais, même race, hors combat).'),
  ('Bénédiction','Sang Sacré','Sang du lanceur bénit : une créature de niveau inférieur qui le cannibalise ne gagne aucun PV. Niv. 11+ : tout drain de vie subi inflige 1 dégât à son lanceur.'),
  ('Bénédiction','Zone Anti-Pathogène','Crée une zone bloquant l''entrée ou la sortie (au choix) des personnes contaminées. Gravité bloquée ↑ avec le niveau (parasite → maladie majeure).'),
  ('Bénédiction','Ancrage de l''âme','Ancre l''âme : toute possession / vol d''âme / nécromancie doit dépasser le niveau du sort. À la mort, l''âme reste ancrée et le compte à rebours de retour à la vie est gelé.'),
  ('Bénédiction','Bénédiction du Seuil','Barrière autour d''un lieu fixe contre une origine au choix (Tombes/Rêves/Néant/Cauchemars) : 1 dégât magique par franchissement ; entrée sur invitation ; le lanceur doit rester dedans.'),
  ('Chaos','Ami/Ennemi','Modifie l''attitude des cibles envers le lanceur (ami ↔ hostile). L''ami cesse toute agression ; l''ennemi ne va pas jusqu''à tuer. Fin si le lanceur agresse une cible.'),
  ('Chaos','Anti-Détection','Immunise cibles ou objets contre les sorts de divination de niveau ≤ au sort. Un sort de connaissance annulé → annoncer « Annule ».'),
  ('Chaos','Avidité','Les cibles cherchent à s''emparer d''un objet visible désigné (jusqu''à tuer selon leur caractère) et à le garder. Conscientes ; fin si inconscientes.'),
  ('Chaos','Dissimulation d''Objet','Les cibles ignorent un objet visible désigné : même en fouillant, il leur paraît invisible ou sans importance.'),
  ('Chaos','Fou Rire Incessant','La cible rit de façon incontrôlable : ne peut ni attaquer ni lancer de sort, se défend mal. Niv. 11+ : aussi « aveuglé ».'),
  ('Chaos','Modification d''Apparence','Modifie l''apparence de la cible pour éviter d''être reconnu (pas une imitation fidèle). Le joueur applique les changements physiques en jeu.'),
  ('Chaos','Rageur Fou','La cible voit tout le monde comme ennemi et attaque sans distinction. Annulé par un sort de calme de niveau supérieur ; fin si inconsciente.'),
  ('Chaos','Toucher de la folie','Inflige l''effet « folie » à la cible touchée : perceptions déformées, murmures imaginaires, difficulté à distinguer le réel de l''illusion.'),
  ('Chaos','Trou de mémoire','Fait oublier à la cible, selon le niveau : ses formules/prières (1), les noms propres (6), un moment des 30 dernières min (11) ou un souvenir de façon permanente (20).'),
  ('Chaos','Bavardage Compulsif','Les cibles ne peuvent plus se taire (parler/chanter/marmonner sans cesse). Fin si inconscientes ou réduites au silence par un sort ≥.'),
  ('Chaos','Confusion de la Loi','Le rayon annule tout sort du domaine de l''Ordre et tout effet de vérité de niveau inférieur.'),
  ('Chaos','Maladresse','Les cibles perdent leur coordination : compétences manuelles inutilisables (forge, alchimie, soins, crochetage, pièges, etc.). Combat et sorts restent possibles.'),
  ('Chaos','Mensonge','La cible ne peut plus dire la vérité (à l''oral comme à l''écrit) et résiste aux effets de vérité de niveau inférieur.'),
  ('Chaos','Perte de compétence d''arme','Toutes les compétences d''arme de la cible sont inutilisables pendant la durée du sort.'),
  ('Chaos','Brouillage du Chaos','Affecte une cible de niveau ≤ au sort : ses sorts de divination/Connaissance lui renvoient des informations fausses ou trompeuses.'),
  ('Chaos','Complication magique','Chaque sort lancé par la cible coûte +1 point de spiritualité (sans bonus d''effet). Niv. 20 : +2.'),
  ('Connaissance','Alerte du Danger','Les cibles résistent aux pièges avec le niveau du sort au lieu du leur.'),
  ('Connaissance','Détection de la famille','Révèle l''origine/famille d''une créature (Tombes, Rêves, Néant, Nature…) si le sort égale ou dépasse son niveau ; sinon impression confuse.'),
  ('Connaissance','Détection de la magie','Confirme la présence ou l''absence d''aura magique (sans nature ni puissance) et détecte les fausses auras. Aura masquée ou portée : exige un niveau ≥.'),
  ('Connaissance','Discernement Divin','Immunise les cibles contre les sorts d''illusion de niveau inférieur. Une illusion annulée → annoncer « Annule ».'),
  ('Connaissance','Don des Langues','La cible comprend et parle les langues qui lui sont inconnues pour la durée du sort.'),
  ('Connaissance','Ange Gardien','Protège un objet déplaçable désigné (ruban jaune) : nul ne peut le saisir sans dépasser le niveau du sort. Fin s''il quitte la vue du lanceur. Un seul objet ; pas contre la destruction.'),
  ('Connaissance','Augure','Pose des questions (oui/non/indécis) à une force supérieure ; nombre = moitié du niveau (arrondi sup.). Nécessite un animateur.'),
  ('Connaissance','Dissipation de la magie','Retire aux cibles tous les effets magiques (sorts, potions) de niveau inférieur. Sans effet sur les objets magiques.'),
  ('Connaissance','Interception des rêves','Lien passif : si la cible utilise la compétence Rêve la nuit suivante, le lanceur perçoit ce rêve (sans le modifier). Un seul lien ; prévenir un animateur avant de dormir.'),
  ('Connaissance','Lecture de l''Âme','Détecte si une créature a une âme et s''il s''agit de la sienne d''origine. Niv. 11+ : perçoit l''origine d''une altération (pacte, malédiction, possession, échange).'),
  ('Connaissance','Suspension de la chair','Met un membre ou organe amputé en stase : +1 cycle avant greffe (2 max au total). Utilisable une seule fois par membre.'),
  ('Connaissance','Vision de la magie','Révèle les écoles et domaines des sorts actuellement actifs sur la cible (sans effets, durée ni niveau).'),
  ('Connaissance','Savoir du Prophète','Lien avec le prophète de sa religion pour poser des questions (nombre/ampleur ↑ avec le niveau, jusqu''à 10 min de discussion). Le prophète peut refuser ou exiger une contrepartie.'),
  ('Éléments','Appel de la Foudre','Inflige 1 → 8 dégâts de foudre selon le niveau.'),
  ('Éléments','Bouclier Élémentaire','Bouclier absorbant (moitié du niveau, arrondi sup.) d''un élément au choix par cible (feu/glace/foudre/acide). L''excédent passe ; un seul bouclier à la fois.'),
  ('Éléments','Colonne de Feu Sacré','Inflige 1 → 6 dégâts de feu béni selon le niveau ; double aux morts-vivants.'),
  ('Éléments','Globe d''Air','Bloque les projectiles physiques (flèches, carreaux, armes de lancer) : nombre ↑ avec le niveau (1 → tous au Niv. 20). Bloquer → pointer + « Annule ».'),
  ('Éléments','Peau de Pierre','Encaisse 1 → 5 coups d''armes non magiques sans dégâts (les assommants comptent ; une attaque sournoise consomme tout le reste). Immunise aussi à la pétrification de niveau inférieur.'),
  ('Éléments','Pétrification/Dépétrification','Pétrifie les cibles : immobiles, muettes, mais perçoivent ; impossible de les blesser. Sert aussi à dépétrifier (si le niveau dépasse celui appliqué).'),
  ('Éléments','Tornade Martiale','Confère « Repoussement 5 pieds » à des armes (1 par cible) pour 1 → 5 coups selon le niveau ; projette la cible vers l''arrière.'),
  ('Éléments','Augmentation du poids','L''objet ciblé ne peut plus être soulevé (objet porté : niveau du sort vs porteur). Niv. 11+ : 2 objets. Niv. 20 : le lanceur n''est pas affecté.'),
  ('Éléments','Bouclier Adaptatif','Réduit le premier effet élémentaire reçu (feu/glace/foudre/acide), puis se verrouille sur cet élément. Réduction 3 → 8 selon le niveau.'),
  ('Éléments','Brasier Vengeur','Si le lanceur tombe à 0 PV, une explosion de feu (2 → 5 dégâts, rayon 5 → 20 pieds) frappe les alentours. Une fois par lancement ; pas en cas de 0 PV volontaire ; lanceur épargné.'),
  ('Éléments','Changement de Température','Les cibles subissent une chaleur ou un froid extrême (jouer 40 °C ou -40 °C) : impossible de se concentrer.'),
  ('Éléments','Noyade','La cible a l''impression de se noyer : à genoux/au sol, ne peut ni parler, ni attaquer, ni incanter, ni utiliser de compétences. Déplacement lent possible.'),
  ('Éléments','Rupture élémentaire','Dissipe tous les sorts bénéfiques élémentaires de niveau ≤ sur la cible (cercles air/feu/eau/terre et domaine des Éléments). Les effets non élémentaires sont épargnés.'),
  ('Éléments','Brasero','Inflige l''état Enflammé : la cible doit consacrer une action à s''éteindre, sinon perd 50 % de ses PV totaux (armure incluse). Une fois par combat.'),
  ('Éléments','Déchaînement Élémentaire','Inflige 4 → 10 dégâts d''un élément au choix (feu/glace/foudre/acide) à toute la zone. Relancer sous 20 s avec un autre élément : coût -1 spiritualité.'),
  ('Guerre','Armure','Confère 1 → 5 points d''armure temporaires selon le niveau (non récupérables, cumulables avec une armure physique).'),
  ('Guerre','Combat Aveugle','Permet au lanceur de combattre sans voir : il peut garder les yeux ouverts même aveuglé.'),
  ('Guerre','Immunité au Poison','Immunise contre les nouveaux poisons (gravité ↑ avec le niveau, mineur → majeur). Niv. 20 : survit au poison mortel (comateux à 0 PV).'),
  ('Guerre','Insensibilité à la douleur','La douleur n''affecte plus la cible (sans réduire les dégâts). Niv. 6+ : immunise à la Torture. Niv. 11+ : les sorts de douleur doivent dépasser le niveau.'),
  ('Guerre','Lenteur','Ralentit la cible de moitié : ses coups n''infligent aucun dégât, elle ne peut que marcher lentement et sa voix devient incompréhensible.'),
  ('Guerre','Présence intimidante','Effet de peur : les cibles ne peuvent ni attaquer ni cibler le lanceur et fuient jusqu''à le perdre de vue (elles peuvent encore se défendre).'),
  ('Guerre','Protection contre les Armes Conventionnelles','Encaisse 1 → 5 coups d''armes non magiques sans dégâts selon le niveau (les assommants comptent ; une attaque sournoise consomme tout le reste).'),
  ('Guerre','Provocation','La cible doit absolument tenter de blesser le lanceur ; l''effet cesse dès qu''elle le fait saigner.'),
  ('Guerre','Sens aiguisé','Bloque une attaque par surprise (annoncer « Annule ») : couverture ↑ avec le niveau (pièges → backstab). Le sort prend fin au blocage, sauf au Niv. 20.'),
  ('Guerre','Arme Magique','Enchante des armes (1 par cible) : dégâts magiques (Niv. 6), indestructible (10), insensible aux sorts (15). Niv. 20 : toutes les armes à 10 pieds frappent magique.'),
  ('Guerre','Fureur Divine','Confère 2 → 5 points d''armure temporaires selon le niveau ; immunise à la peur de niveau inférieur tant que l''armure tient.'),
  ('Guerre','Gardien Dévot','Le lanceur encaisse à la place de la cible les dégâts qui la viseraient (il doit la regarder ; son armure absorbe d''abord).'),
  ('Guerre','Poigne de fer','Les cibles peuvent manier des armes à deux mains sans en avoir la compétence. Niv. 11+ : ne peuvent plus être désarmées.'),
  ('Guerre','Sanctuaire','Empêche les personnages de niveau ≤ d''approcher à moins de 10 pieds (sauf ceux autorisés). Le lanceur ne doit pas bouger ; sans effet sur projectiles et sorts.'),
  ('Guerre','Châtiment du Traître','Empêche la cible de recevoir tout sort bénéfique de niveau inférieur (n''enlève pas ceux déjà actifs).'),
  ('Nature','Armure de Bois','Confère 1 → 6 points d''armure temporaires selon le niveau (non récupérables) ; inopérant si la cible porte déjà une armure physique.'),
  ('Nature','Baies de Guérison','Enchante des petits fruits (nombre ↑ avec le niveau) ; chacun rend 1 PV une fois mangé. Sans effet après expiration.'),
  ('Nature','Bâton de Protection','Enchante un bâton travaillé (≥ 4 pieds) : tant qu''il est porté, il résiste aux sorts de niveau inférieur. Prend fin au premier sort bloqué.'),
  ('Nature','Cocotte Magique','Enchante des cocottes de pin (nombre ↑ avec le niveau) ; chacune inflige 1 dégât magique lorsqu''elle est lancée.'),
  ('Nature','Communion avec la Nature','Communique avec une entité naturelle au choix : elle répond par oui/non/indécis. Nombre de questions ↑ avec le niveau.'),
  ('Nature','Enchevêtrement','Immobilise les cibles dans des lianes indestructibles (ni coupées ni brûlées). Seule la fin du sort ou une dissipation y met fin.'),
  ('Nature','Ennemi de la Nature','La cible ne peut pas s''approcher à moins de 3 pieds des bois : elle doit rester sur les chemins et les constructions.'),
  ('Nature','Enterrement magique','Ensevelit magiquement un corps mort dans le sol en 1 minute. N''empêche pas de le déterrer, le piller ni le relever en zombie.'),
  ('Nature','Essaim Vorace','Une nuée d''insectes harcèle la cible : aucune action offensive possible, elle ne peut que se défendre, reculer ou chasser les insectes.'),
  ('Nature','Passage sans Trace','Les cibles ne laissent aucune trace : seul un personnage avec Pistage ou Flair affûté de niveau ≥ peut les suivre. Cibles ↑ avec le niveau.'),
  ('Nature','Traque Bestiale','Confère le trait « Flair affûté » au lanceur (partageable avec des alliés aux niveaux supérieurs, formant une meute).'),
  ('Nature','Envoûtement de Créature','Une créature monstrueuse vivante obéit au lanceur comme à une autorité, sans jamais se mettre en danger ni courir à sa mort.'),
  ('Nature','Esprit animal','Confère un trait racial Chimérides au choix (affinité animale, charognard, flair affûté, instinct de survie). Comportement sauvage ; masque/maquillage animal obligatoire.'),
  ('Nature','Odeur Infecte','Crée autour du lanceur une zone que nul ne peut approcher tant l''odeur est répugnante.'),
  ('Nature','Sang de la Terre','Si la cible tombe à 0 PV, elle régénère au sol : +1 PV/min pendant 5 min et reprend conscience en 5 min (sans souvenir). Extérieur seulement ; se réactive.'),
  ('Nature','Marque de la menace','Marque une cible : les sorts à effet du domaine de la Nature la visant gagnent +1 à +3 niveaux effectifs (plafond 20). À appliquer soi-même ; pas sur soi.'),
  ('Nature','Serment de la terre Mère','Cercle : les alliés dans la zone bloquent la nécromancie de niveau inférieur et échappent aux sorts de zone de Nature du lanceur. Lanceur immobile ; sans effet sous un toit.'),
  ('Nécromancie','Animation des morts','Relève des cibles mortes ou comateuses en morts-vivants sous contrôle du lanceur (type ↑ avec le niveau : zombie → spectre). Comateux : se réveille après 1 min sans souvenir.'),
  ('Nécromancie','Bouclier Contre la Mort','Bouclier annulant les dégâts de vol de vie (drainlife), à hauteur de la moitié du niveau (arrondi sup.).'),
  ('Nécromancie','Communication avec les Cadavres','Interroge un mort (tête au minimum requise) : il répond à voix haute. Nombre de questions ↑ avec le niveau (1 → 5). Hors combat seulement.'),
  ('Nécromancie','Contact avec les Anciens','Communique avec un fantôme au choix (objet lui ayant appartenu requis) : discussion complète, il ne peut mentir. Nécessite un animateur.'),
  ('Nécromancie','Destruction des Morts-Vivants','Inflige aux morts-vivants des dégâts magiques égaux au niveau du sort.'),
  ('Nécromancie','Guérison des Morts-Vivants','Soigne les morts-vivants de 1 PV par niveau du sort. Sans effet sur les vivants.'),
  ('Nécromancie','Masque Funèbre','Fait paraître les cibles mortes (signes vitaux faussés). Niveau de Diagnostic trompé ↑ avec le niveau (jusqu''à Diagnostic 3). La cible peut agir normalement.'),
  ('Nécromancie','Simulacre de vie','Fait paraître les cibles vivantes et entières (signes vitaux simulés). Niveau de Diagnostic trompé ↑ avec le niveau (jusqu''à Diagnostic 3).'),
  ('Nécromancie','Contrôle des Morts-Vivants','Prend le contrôle de morts-vivants : ils obéissent à la lettre, même au péril de leur « vie ». Pour reprendre un mort-vivant déjà contrôlé : niveau ≥ au sort en cours.'),
  ('Nécromancie','Drain de vie','Inflige 1 → 4 dégâts selon le niveau et soigne le lanceur d''autant (jamais au-delà du max). Niv. 20 : peut transférer ses PV à un allié consentant à 5 pieds.'),
  ('Nécromancie','Paralysie de Morts-Vivants','Immobilise les morts-vivants (ils perçoivent mais ne parlent plus). Tout dégât subi dissipe l''effet.'),
  ('Nécromancie','Répulsion des morts-vivants','Empêche les morts-vivants de niveau inférieur d''approcher à moins de 5 pieds du lanceur. Affecte tous les morts-vivants, alliés compris.'),
  ('Nécromancie','Capture d''Âmes','Emprisonne l''âme d''un personnage mort dans une pierre d''âme (objet en jeu) ; la briser libère l''âme. Exige un niveau ≥ à celui de la cible.'),
  ('Nécromancie','Puits de Putréfaction','Zone fixe d''énergie négative : les vivants subissent 1 → 4 dégâts à l''entrée puis chaque minute ; les morts-vivants y récupèrent +1 → +5 PV. Effet stoppé en sortant.'),
  ('Nécromancie','Retour à la Vie','Ramène un mort à la vie à 1 PV (exige un niveau ≥ à la cible ; délai depuis la mort selon la durée choisie). Inutile sur un comateux/inconscient.'),
  ('Ordre','Bulle d''emprisonnement','Bulle de force bloquant personnages, attaques physiques et sorts (déplacement et parole possibles à l''intérieur). Percée et terminée par un niveau supérieur.'),
  ('Ordre','Calme','Calme les cibles et stoppe les effets de rage (Berzerk, Rageur Fou, Antipathie, Avidité). Les ordres d''agressivité d''un contrôle mental cessent d''agir.'),
  ('Ordre','Délivrance des Envoûtements','Dissipe des cibles tous les effets de Charme et d''Illusion de niveau inférieur ou égal au sort.'),
  ('Ordre','Discours captivant','Force les cibles à fixer le lanceur tant qu''il parle ou joue sans cesse (fin après 10 s de silence). Un dégât ou choc physique libère la cible touchée.'),
  ('Ordre','Esprit Inviolable','Les cibles résistent aux sorts de Charme avec le niveau du sort au lieu du leur. N''annule pas les effets déjà actifs.'),
  ('Ordre','Pieu Spirituel','Rend tangibles les cibles intangibles et les empêche de le redevenir pendant la durée du sort.'),
  ('Ordre','Vérité','Les cibles ne peuvent plus mentir volontairement (mais ne sont pas obligées de parler).'),
  ('Ordre','Bannissement','Repousse les entités d''un autre monde (niveau ≥ requis). Niv. 6 : morts-vivants inconscients 5 min ou renvoyés dans leur corps. Niv. 11+ : créatures extraplanaires détruites ou renvoyées.'),
  ('Ordre','Délivrance des Malédictions','Dissipe des cibles tous les effets de malédiction de niveau inférieur ou égal au sort.'),
  ('Ordre','Interrogatoire','Les cibles ne peuvent mentir et doivent répondre aux questions. Nombre de questions ↑ avec le niveau (1 → 6).'),
  ('Ordre','Justice céleste','Interdit à la cible toute attaque (même défensive) contre quiconque, sauf les monstres non humanoïdes.'),
  ('Ordre','Paralysie','Immobilise les cibles (elles perçoivent mais ne parlent plus). Tout dégât subi dissipe l''effet.'),
  ('Ordre','Sacrifice de soi','Le prêtre prend sur lui l''affliction d''une cible (avec tous ses malus) : poison (Niv. 6), + maladie (11), + malédiction (16). Niv. 20 : absorbe un coup de grâce subi dans les 2 min.'),
  ('Ordre','Injonction','La cible suit à la lettre les instructions du lanceur, sauf celles qui causeraient sa blessure ou sa mort imminente.'),
  ('Ordre','Verrou de la loi','Empêche la cible de lancer les sorts d''une école ou d''un domaine choisi (fixé au lancement). N''annule pas les effets déjà actifs.')
) AS v(domaine, nom, courte)
WHERE p.domaine = v.domaine
  AND p.nom = v.nom
  AND p.description_courte IS DISTINCT FROM v.courte;
